# Generated by Django 2.2 on 2020-07-05 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('end_date', models.DateField(verbose_name='Fecha de finalización')),
                ('note', models.TextField(max_length=250, verbose_name='Nota')),
                ('adjunto', models.FileField(blank=True, null=True, upload_to='')),
                ('task', models.BooleanField(default=False)),
                ('tipo', models.CharField(choices=[('1', 'TIPO 1'), ('2', 'TIPO 2'), ('3', 'TIPO 3')], max_length=7)),
                ('tags', models.ManyToManyField(blank=True, related_name='tags', to='notes.Tag')),
                ('user', models.ManyToManyField(blank=True, related_name='notes', to='notes.User')),
            ],
        ),
    ]
